export const PRODUCTS_ACTION_TYPES = {
  PRODUCTS_START: "PRODUCTS_START",
  PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
  PRODUCTS_ERROR: "PRODUCTS_ERROR",
  PRODUCTS_SEARCH_AND_FILTER: "PRODUCTS_SEARCH_AND_FILTER",
  PRODUCTS_FILTER_BY_PRICE: "PRODUCTS_FILTER_BY_PRICE",
  PRODUCTS_SORT: "PRODUCTS_SORT",
};
