const PRODUCT_DATA = [
  {
    title: "Bags",
    items: [
      {
        id: 1,
        name: "adidas black bag",
        image: "/images/adidas-bag-1.jpg",
        price: 70,
        rating: 4.3,
        category: "bag",
        brand: "adidas",
        color: "black",
      },
      {
        id: 2,
        name: "adidas olive green bag",
        image: "/images/adidas-bag-2.jpg",
        price: 85,
        rating: 4.9,
        category: "bag",
        brand: "adidas",
        color: "green",
      },
      {
        id: 3,
        name: " adidas grey bag",
        image: "/images/adidas-bag-3.jpg",
        price: 60,
        rating: 5,
        category: "bag",
        brand: "adidas",
        color: "grey",
      },
      {
        id: 4,
        name: " nike black bag",
        image: "/images/nike-bag-1.jpg",
        price: 70,
        rating: 4.8,
        category: "bag",
        brand: "nike",
        color: "black",
      },
      {
        id: 5,
        name: " nike pink bag",
        image: "/images/nike-bag-2.jpg",
        price: 85,
        rating: 5,
        category: "bag",
        brand: "nike",
        color: "pink",
      },
      {
        id: 6,
        name: " puma black bag",
        image: "/images/puma-bag-1.jpg",
        price: 60,
        rating: 4.8,
        category: "bag",
        brand: "puma",
        color: "black",
      },
      {
        id: 7,
        name: " puma darkblue bag",
        image: "/images/puma-bag-2.jpg",
        price: 65,
        rating: 3.4,
        category: "bag",
        brand: "puma",
        color: "darkblue",
      },
      {
        id: 8,
        name: " puma lightblue bag",
        image: "/images/puma-bag-3.jpg",
        price: 55,
        rating: 4.4,
        category: "bag",
        brand: "puma",
        color: "lightblue",
      },
    ],
  },
  {
    title: "Hats",
    items: [
      {
        id: 9,
        name: "adidas blue hat",
        image: "/images/adidas-hat-1.jpg",
        price: 25,
        rating: 4.6,
        category: "hat",
        brand: "adidas",
        color: "blue",
      },
      {
        id: 10,
        name: "adidas black hat",
        image: "/images/adidas-hat-2.jpg",
        price: 20,
        rating: 4.3,
        category: "hat",
        brand: "adidas",
        color: "black",
      },
      {
        id: 11,
        name: "adidas white hat",
        image: "/images/adidas-hat-3.jpg",
        price: 20,
        rating: 5,
        category: "hat",
        brand: "adidas",
        color: "white",
      },
      {
        id: 12,
        name: "adidas white hat",
        image: "/images/adidas-hat-4.jpg",
        price: 30,
        rating: 5,
        category: "hat",
        brand: "adidas",
        color: "white",
      },
      {
        id: 13,
        name: "nike blue hat",
        image: "/images/nike-hat-1.png",
        price: 30,
        rating: 4.1,
        category: "hat",
        brand: "nike",
        color: "white",
      },
      {
        id: 14,
        name: "nike green hat",
        image: "/images/nike-hat-2.png",
        price: 30,
        rating: 4.7,
        category: "hat",
        brand: "nike",
        color: "white",
      },
      {
        id: 15,
        name: "nike black hat",
        image: "/images/nike-hat-3.png",
        price: 30,
        rating: 4.3,
        category: "hat",
        brand: "nike",
        color: "black",
      },
    ],
  },
  {
    title: "Jackets",
    items: [
      {
        id: 16,
        name: "Adidas Black Jacket",
        image: "/images/adidas-jacket-1.jpg",
        price: 110,
        rating: 4.5,
        category: "jacket",
        brand: "adidas",
        color: "black",
      },
      {
        id: 17,
        name: "Adidas White Jacket",
        image: "/images/adidias-jacket-2.jpg",
        price: 80,
        rating: 3.5,
        category: "jacket",
        brand: "adidas",
        color: "white",
      },
      {
        id: 18,
        name: "Nike Blue Jacket",
        image: "/images/nike-jacket-1.png",
        price: 150,
        rating: 5,
        category: "jacket",
        brand: "nike",
        color: "blue",
      },
      {
        id: 19,
        name: "Nike White Jacket",
        image: "/images/nike-jacket-2.jpg",
        price: 120,
        rating: 5,
        category: "jacket",
        brand: "nike",
        color: "white",
      },
      {
        id: 20,
        name: "Nike Brown Jacket",
        image: "/images/nike-jacket-3.jpg",
        price: 170,
        rating: 4.5,
        category: "jacket",
        brand: "nike",
        color: "Brown",
      },
      {
        id: 21,
        name: "Nike Olive Green Jacket",
        image: "/images/nike-jacket-4.jpg",
        price: 170,
        rating: 5,
        category: "jacket",
        brand: "nike",
        color: "green",
      },
    ],
  },
];

export default PRODUCT_DATA;
