const PRODUCT_DATA = [
  {
    name: "adidas black bag",
    image: "/images/adidas-bag-1.jpg",
    price: 70,
    rating: 4.3,
    category: "bag",
    brand: "adidas",
    color: "black",
    size: ["S", "M", "L", "XL", "XLL"],
  },
  {
    name: "adidas olive green bag",
    image: "/images/adidas-bag-2.jpg",
    price: 85,
    rating: 4.9,
    category: "bag",
    brand: "adidas",
    color: "green",
    size: ["S", "M", "L", "XL"],
  },
  {
    name: " adidas grey bag",
    image: "/images/adidas-bag-3.jpg",
    price: 60,
    rating: 5,
    category: "bag",
    brand: "adidas",
    color: "grey",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: " nike black bag",
    image: "/images/nike-bag-1.jpg",
    price: 70,
    rating: 4.8,
    category: "bag",
    brand: "nike",
    color: "black",
    size: ["S", "M", "L", "XL", "XLL"],
  },
  {
    name: " nike pink bag",
    image: "/images/nike-bag-2.jpg",
    price: 85,
    rating: 5,
    category: "bag",
    brand: "nike",
    color: "pink",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: " puma black bag",
    image: "/images/puma-bag-1.jpg",
    price: 60,
    rating: 4.8,
    category: "bag",
    brand: "puma",
    color: "black",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: " puma darkblue bag",
    image: "/images/puma-bag-2.jpg",
    price: 65,
    rating: 3.4,
    category: "bag",
    brand: "puma",
    color: "darkblue",
    size: ["S", "M", "L"],
  },
  {
    name: " puma lightblue bag",
    image: "/images/puma-bag-3.jpg",
    price: 55,
    rating: 4.4,
    category: "bag",
    brand: "puma",
    color: "lightblue",
    size: ["S", "M", "L", "XL"],
  },
  {
    name: "adidas blue hat",
    image: "/images/adidas-hat-1.jpg",
    price: 25,
    rating: 4.6,
    category: "hat",
    brand: "adidas",
    color: "blue",
    size: ["S", "M"],
  },
  {
    name: "adidas black hat",
    image: "/images/adidas-hat-2.jpg",
    price: 20,
    rating: 4.3,
    category: "hat",
    brand: "adidas",
    color: "black",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "adidas white hat",
    image: "/images/adidas-hat-3.jpg",
    price: 20,
    rating: 5,
    category: "hat",
    brand: "adidas",
    color: "white",
    size: ["S", "M", "L", "XL"],
  },
  {
    name: "adidas white hat",
    image: "/images/adidas-hat-4.jpg",
    price: 30,
    rating: 5,
    category: "hat",
    brand: "adidas",
    color: "white",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "nike blue hat",
    image: "/images/nike-hat-1.png",
    price: 30,
    rating: 4.1,
    category: "hat",
    brand: "nike",
    color: "white",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "nike green hat",
    image: "/images/nike-hat-2.png",
    price: 30,
    rating: 4.7,
    category: "hat",
    brand: "nike",
    color: "white",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "nike black hat",
    image: "/images/nike-hat-3.png",
    price: 30,
    rating: 4.3,
    category: "hat",
    brand: "nike",
    color: "black",
    size: ["S", "M", "L", "XL", "XLL"],
  },
  {
    name: "Adidas Black Jacket",
    image: "/images/adidas-jacket-1.jpg",
    price: 110,
    rating: 4.5,
    category: "jacket",
    brand: "adidas",
    color: "black",
    size: ["S", "M", "L"],
  },
  {
    name: "Adidas White Jacket",
    image: "/images/adidas-jacket-2.jpg",
    price: 80,
    rating: 3.5,
    category: "jacket",
    brand: "adidas",
    color: "white",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "Nike Blue Jacket",
    image: "/images/nike-jacket-1.png",
    price: 150,
    rating: 5,
    category: "jacket",
    brand: "nike",
    color: "blue",
    size: ["S", "M", "L", "XL"],
  },
  {
    name: "Nike White Jacket",
    image: "/images/nike-jacket-2.jpg",
    price: 120,
    rating: 5,
    category: "jacket",
    brand: "nike",
    color: "white",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "Nike Brown Jacket",
    image: "/images/nike-jacket-3.jpg",
    price: 170,
    rating: 4.5,
    category: "jacket",
    brand: "nike",
    color: "Brown",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
  {
    name: "Nike Olive Green Jacket",
    image: "/images/nike-jacket-4.jpg",
    price: 170,
    rating: 5,
    category: "jacket",
    brand: "nike",
    color: "green",
    size: ["S", "M", "L", "XL", "XLL", "3XL"],
  },
];

export default PRODUCT_DATA;
